"""Packaging hygiene checks for production source files."""

from __future__ import annotations

import py_compile
import subprocess
from pathlib import Path


def test_every_python_source_in_package_compiles(tmp_path: Path) -> None:
    """Catch stale backup modules and other syntax errors outside imports."""
    package_dir = Path(__file__).parents[1] / "ai_project_manager"

    for source in package_dir.rglob("*.py"):
        relative = source.relative_to(package_dir)
        target = tmp_path / relative.with_suffix(".pyc")
        target.parent.mkdir(parents=True, exist_ok=True)
        py_compile.compile(str(source), cfile=str(target), doraise=True)


def test_git_does_not_track_generated_python_artifacts() -> None:
    """Generated bytecode makes reviews noisy and is not portable."""
    repository = Path(__file__).parents[1]
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=repository,
        check=True,
        capture_output=True,
    )
    tracked = [Path(raw.decode()) for raw in result.stdout.split(b"\0") if raw]

    offenders = [
        str(path)
        for path in tracked
        if "__pycache__" in path.parts or path.suffix == ".pyc"
    ]
    assert offenders == []
